"""revision

Revision ID: 79012adff541
Revises: 983360ac29b9
Create Date: 2025-01-29 12:10:27.859983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79012adff541'
down_revision: Union[str, None] = '983360ac29b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_user_associations', sa.Column('rent_start_date', sa.DateTime(), nullable=False))
    op.add_column('book_user_associations', sa.Column('rent_end_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_user_associations', 'rent_end_date')
    op.drop_column('book_user_associations', 'rent_start_date')
    # ### end Alembic commands ###
